const fs = require('fs');
const assert = require('assert');

const manifest = JSON.parse(fs.readFileSync('manifest.json', 'utf8'));
const html = fs.readFileSync('newtab.html', 'utf8');
const dashboard = fs.readFileSync('advanced-dashboard.js', 'utf8');
const avatar = fs.readFileSync('avatar.js', 'utf8');
const avatarDialogue = JSON.parse(fs.readFileSync('avatar-dialogue.json', 'utf8'));

assert.equal(manifest.manifest_version, 3);
assert(manifest.permissions.includes('bookmarks'));
assert(html.includes('id="wet-glass-canvas"'));
assert(html.includes('id="command-overlay"'));
assert(html.includes('control-group-dashboard'));
assert(html.indexOf('id="rain-test-btn"') > html.indexOf('class="header-controls"'), 'Rain test control belongs in the header');
assert(html.includes('advanced-dashboard.js'));
assert(dashboard.includes("['http:', 'https:']"), 'URL protocol allowlist must remain present');
assert(dashboard.includes('widgetCloseMap'), 'Every widget must receive a direct close action');
assert(dashboard.includes('mergeDrops()'), 'Wet-glass rain must support merging drops');
assert(dashboard.includes('windTarget'), 'Wet-glass rain must support changing lateral wind');
assert(dashboard.includes("globalCompositeOperation = 'screen'"), 'Drops must retain a separate optical highlight pass');
assert(dashboard.includes('staticBead'), 'Static beads and travelling drops must use distinct silhouettes');
assert(dashboard.includes('preserveTrail(drop)'), 'Trails must be able to outlive their parent drop');
assert(dashboard.includes('splitDrop(drop)'), 'Large drops must split instead of growing without bound');
assert(!dashboard.includes('j % 9'), 'Streaks must not contain repeated satellite circles');
assert(dashboard.includes("lineCap = 'butt'"), 'Streak segments must not render as strings of round caps');
assert(!html.includes('workspace-profile'), 'Workspace profiles must remain removed');
assert(html.includes('id="tab-appearance"'), 'Appearance controls belong in Settings');
assert(!html.includes('fonts.googleapis.com'), 'Extension pages must not load remote fonts');
assert(html.includes('id="avatar-canvas"'), 'The 3D companion needs its own non-interactive canvas');
assert(html.includes('id="avatar-hit-target"'), 'The avatar needs a bounded interaction target without blocking the page');
assert(html.includes('id="avatar-test-sequence"'), 'The temporary avatar test sequence must remain available during review');
assert(html.includes('avatar.js'), 'The avatar controller must load after the page systems');
assert(avatar.includes('RocketBackpackModule'), 'The avatar must include its rocket backpack');
assert(avatar.includes("this.phase = 'rebuilding'"), 'The avatar must support magnetic rebuilding');
assert(avatar.includes('getAnchors()'), 'Avatar actions must resolve live DOM anchors');
assert(avatar.includes('prefers-reduced-motion'), 'Avatar movement must respect reduced motion');
assert(avatar.includes("this.phase = 'thrown'"), 'Dragging Pip must preserve release velocity as a ragdoll throw');
assert(avatar.includes('collisionSurfaces()'), 'Ragdoll drops must collide with page surfaces');
assert(avatar.includes('beginWave()'), 'Clicking Pip must trigger a wave');
assert(Array.isArray(avatarDialogue.rocket) && avatarDialogue.rocket.length > 1, 'Rocket dialogue must ship as editable data');
console.log('Chrome Home smoke tests passed');
